# Autogenerated helper to run the FastAPI app without worrying about folder names with spaces.
# Usage: python run.py
import sys
import pathlib
proj_root = pathlib.Path(__file__).resolve().parent
# Add 'docs scrapping' dir to sys.path so Python can import 'app' package inside it
docs_scrapping = proj_root / "docs scrapping"
if docs_scrapping.exists():
    sys.path.insert(0, str(docs_scrapping))
else:
    # Fallback: if app is at project root under 'app'
    sys.path.insert(0, str(proj_root))
# Now run uvicorn programmatically
try:
    import uvicorn
except Exception as e:
    print("uvicorn not installed in this environment. Install it or run using your virtualenv.")
    raise

if __name__ == "__main__":
    # Use module path 'app.main:app'
    uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=True)