import json
import re
from app.llm.client import run_llm
from app.agent.resources import get_heading_documentation


# ==========================================
# SAFE JSON EXTRACTOR
# ==========================================

def extract_json(text: str):
    """
    Extract the first JSON object found in text.
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        return match.group(0)
    return None


# ==========================================
# STRICT JSON STUDY PLANNER
# ==========================================

def plan_topics(goal: str, days: int):

    prompt = f"""
You are an academic curriculum designer.

Create a structured study roadmap for:

{goal}

IMPORTANT:

- Output MUST be valid JSON.
- Do NOT write explanations.
- Do NOT write introduction text.
- Do NOT write "Here is the roadmap".
- Do NOT write anything outside JSON.
- Do NOT use markdown.
- Only return JSON.

JSON FORMAT:

{{
  "topics": [
    {{
      "name": "Main Heading",
      "subtopics": [
        "Subtopic 1",
        "Subtopic 2",
        "Subtopic 3"
      ]
    }}
  ]
}}

Generate clean academic headings required to master the subject.
"""

    raw_response = run_llm("llama3:8b", prompt)

    # Remove markdown wrappers if present
    raw_response = raw_response.replace("```json", "").replace("```", "").strip()

    # Extract JSON block safely
    json_text = extract_json(raw_response)

    if not json_text:
        raise Exception(f"Could not extract JSON from LLM response:\n{raw_response}")

    try:
        parsed = json.loads(json_text)
    except json.JSONDecodeError as e:
        raise Exception(f"Invalid JSON returned by LLM:\n{json_text}\nError: {e}")

    if "topics" not in parsed:
        raise Exception("Invalid JSON structure returned by LLM.")

    topics = parsed["topics"]

    if not topics:
        raise Exception("No topics generated by LLM.")

    days_per_topic = max(1, days // len(topics))

    final_topics = []

    for topic in topics:

        topic_data = {
            "name": topic["name"],
            "days": days_per_topic,
            "resources": {
                "documentation": get_heading_documentation(topic["name"])
            },
            "subtopics": topic.get("subtopics", [])
        }

        final_topics.append(topic_data)

    return {"topics": final_topics}
